#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $TORNADO_REPO == "tornadobot" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RIRVRPUk5BRE9URUFNL1RPUk5BRE8tVVNFUkJPVC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $TORNADO_REPO == "TORNADOBOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RIRVRPUk5BRE9URUFNL1RPUk5BRE8tVVNFUkJPVC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    elif [[ $TORNADO_REPO =~ $regex ]]
    then
        if [[ $TORNADO_REPO_BRANCH ]]
        then
            echo "${TORNADO_REPO}/archive/${TORNADO_REPO_BRANCH}.zip"
        else
            echo "${TORNADO_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RIRVRPUk5BRE9URUFNL1RPUk5BRE8tVVNFUkJPVC9hcmNoaXZlL21hc3Rlci56aXA=" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="tornadobot.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    TORNADOPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $TORNADOPATH
    echo "    Starting TornadoBot    "
    echo "
                          ╔═╦═╦══╦══╦══╦══╦══╦═╦══╗
                          ║║║║║╔╗║═╦╩║║╣╔╗║╔╗║║╠╗╔╝
                          ║║║║║╠╣║╔╝╔║║╣╠╣║╔╗║║║║║
                          ╚╩═╩╩╝╚╩╝─╚══╩╝╚╩══╩═╝╚╝
    "

    python3 ./setup/updater.py ./requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
